/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bitcamp.myproject;

public class App {
   public static void main(String[] args) {
        
     System.out.println("번호: 1");
     System.out.println("국가: 미국");
     System.out.println("장르: 범죄");
     System.out.println("제목한글: 브레이킹배드");
     System.out.println("제목영문: Breaking Bad");
     System.out.println("제목별칭: 브배, 브베");
     System.out.println("별점: ★★★★★");
     System.out.println("코멘트: 죽기 전에 꼭 봐야할 개명작");
     System.out.println("키워드: #범죄 #마약 #드라마 #명작 #미드 #명연기 #웰메이드");
     System.out.println("상태: 완결");
     System.out.println("2020현재시즌: 05x16");
     System.out.println("어디까지봤니: 05x16");
     
    }
}
