/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bitcamp.myproject;

public class App3 {
   public static void main(String[] args) {
        
     System.out.println("번호: 1");
     System.out.println("제목: 게시글제목");
     System.out.println("내용: 게시글내용입니다.");
     System.out.println("작성일: 2019-12-10");
     System.out.println("조회수: 0");
     System.out.println("댓글: 0");
     
    }
}
