/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bitcamp.myproject;

public class App2 {
   public static void main(String[] args) {
        
     System.out.println("번호: 1");
     System.out.println("이름: 신나라");
     System.out.println("이메일: narashin547@gmail.com");
     System.out.println("암호: narashin547");
     System.out.println("사진: shin.png");
     System.out.println("전화: 010-6823-5479");
     System.out.println("가입일: 2019-12-10");
     
    }
}
